// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user/UserDetails.proto

package com.google.googleidentity.user;

public final class UserDetailsOuterClass {
  private UserDetailsOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_googleidentity_user_UserDetails_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_googleidentity_user_UserDetails_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026user/UserDetails.proto\022\023googleidentity" +
      ".user\"@\n\013UserDetails\022\020\n\010username\030\001 \001(\t\022\020" +
      "\n\010password\030\002 \001(\t\022\r\n\005email\030\003 \001(\tB\"\n\036com.g" +
      "oogle.googleidentity.userP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_googleidentity_user_UserDetails_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_googleidentity_user_UserDetails_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_googleidentity_user_UserDetails_descriptor,
        new java.lang.String[] { "Username", "Password", "Email", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
