// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ClientDetails.proto

package com.google.googleidentity.oauth2.client;

public final class ClientDetailsOuterClass {
  private ClientDetailsOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_googleidentity_oauth2_client_ClientDetails_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_googleidentity_oauth2_client_ClientDetails_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023ClientDetails.proto\022\034googleidentity.oa" +
      "uth2.client\"\177\n\rClientDetails\022\021\n\tclient_i" +
      "d\030\001 \001(\t\022\016\n\006secret\030\002 \001(\t\022\023\n\013grant_types\030\003" +
      " \003(\t\022\021\n\tis_scoped\030\004 \001(\010\022\r\n\005scope\030\005 \003(\t\022\024" +
      "\n\014redirect_uri\030\006 \001(\tB+\n\'com.google.googl" +
      "eidentity.oauth2.clientP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_googleidentity_oauth2_client_ClientDetails_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_googleidentity_oauth2_client_ClientDetails_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_googleidentity_oauth2_client_ClientDetails_descriptor,
        new java.lang.String[] { "ClientId", "Secret", "GrantTypes", "IsScoped", "Scope", "RedirectUri", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
