// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ClientDetails.proto

package com.google.googleidentity.oauth2.client;

/**
 * <pre>
 * Metadata about an OAuth client registered with this server.
 * </pre>
 *
 * Protobuf type {@code googleidentity.oauth2.client.ClientDetails}
 */
public final class ClientDetails extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:googleidentity.oauth2.client.ClientDetails)
    ClientDetailsOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ClientDetails.newBuilder() to construct.
  private ClientDetails(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ClientDetails() {
    clientId_ = "";
    secret_ = "";
    grantTypes_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    scope_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    redirectUri_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ClientDetails();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ClientDetails(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            clientId_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            secret_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              grantTypes_ = new com.google.protobuf.LazyStringArrayList();
              mutable_bitField0_ |= 0x00000001;
            }
            grantTypes_.add(s);
            break;
          }
          case 32: {

            isScoped_ = input.readBool();
            break;
          }
          case 42: {
            java.lang.String s = input.readStringRequireUtf8();
            if (!((mutable_bitField0_ & 0x00000002) != 0)) {
              scope_ = new com.google.protobuf.LazyStringArrayList();
              mutable_bitField0_ |= 0x00000002;
            }
            scope_.add(s);
            break;
          }
          case 50: {
            java.lang.String s = input.readStringRequireUtf8();

            redirectUri_ = s;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        grantTypes_ = grantTypes_.getUnmodifiableView();
      }
      if (((mutable_bitField0_ & 0x00000002) != 0)) {
        scope_ = scope_.getUnmodifiableView();
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.google.googleidentity.oauth2.client.ClientDetailsOuterClass.internal_static_googleidentity_oauth2_client_ClientDetails_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.google.googleidentity.oauth2.client.ClientDetailsOuterClass.internal_static_googleidentity_oauth2_client_ClientDetails_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.google.googleidentity.oauth2.client.ClientDetails.class, com.google.googleidentity.oauth2.client.ClientDetails.Builder.class);
  }

  public static final int CLIENT_ID_FIELD_NUMBER = 1;
  private volatile java.lang.Object clientId_;
  /**
   * <code>string client_id = 1;</code>
   * @return The clientId.
   */
  @java.lang.Override
  public java.lang.String getClientId() {
    java.lang.Object ref = clientId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      clientId_ = s;
      return s;
    }
  }
  /**
   * <code>string client_id = 1;</code>
   * @return The bytes for clientId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getClientIdBytes() {
    java.lang.Object ref = clientId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      clientId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SECRET_FIELD_NUMBER = 2;
  private volatile java.lang.Object secret_;
  /**
   * <code>string secret = 2;</code>
   * @return The secret.
   */
  @java.lang.Override
  public java.lang.String getSecret() {
    java.lang.Object ref = secret_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      secret_ = s;
      return s;
    }
  }
  /**
   * <code>string secret = 2;</code>
   * @return The bytes for secret.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSecretBytes() {
    java.lang.Object ref = secret_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      secret_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int GRANT_TYPES_FIELD_NUMBER = 3;
  private com.google.protobuf.LazyStringList grantTypes_;
  /**
   * <pre>
   * The OAuth 2.0 grant types that are permitted by this client.
   * </pre>
   *
   * <code>repeated string grant_types = 3;</code>
   * @return A list containing the grantTypes.
   */
  public com.google.protobuf.ProtocolStringList
      getGrantTypesList() {
    return grantTypes_;
  }
  /**
   * <pre>
   * The OAuth 2.0 grant types that are permitted by this client.
   * </pre>
   *
   * <code>repeated string grant_types = 3;</code>
   * @return The count of grantTypes.
   */
  public int getGrantTypesCount() {
    return grantTypes_.size();
  }
  /**
   * <pre>
   * The OAuth 2.0 grant types that are permitted by this client.
   * </pre>
   *
   * <code>repeated string grant_types = 3;</code>
   * @param index The index of the element to return.
   * @return The grantTypes at the given index.
   */
  public java.lang.String getGrantTypes(int index) {
    return grantTypes_.get(index);
  }
  /**
   * <pre>
   * The OAuth 2.0 grant types that are permitted by this client.
   * </pre>
   *
   * <code>repeated string grant_types = 3;</code>
   * @param index The index of the value to return.
   * @return The bytes of the grantTypes at the given index.
   */
  public com.google.protobuf.ByteString
      getGrantTypesBytes(int index) {
    return grantTypes_.getByteString(index);
  }

  public static final int IS_SCOPED_FIELD_NUMBER = 4;
  private boolean isScoped_;
  /**
   * <pre>
   * Whether scopes for this client is limited
   * </pre>
   *
   * <code>bool is_scoped = 4;</code>
   * @return The isScoped.
   */
  @java.lang.Override
  public boolean getIsScoped() {
    return isScoped_;
  }

  public static final int SCOPE_FIELD_NUMBER = 5;
  private com.google.protobuf.LazyStringList scope_;
  /**
   * <pre>
   * The OAuth 2.0 scopes that are permitted by this client.
   * </pre>
   *
   * <code>repeated string scope = 5;</code>
   * @return A list containing the scope.
   */
  public com.google.protobuf.ProtocolStringList
      getScopeList() {
    return scope_;
  }
  /**
   * <pre>
   * The OAuth 2.0 scopes that are permitted by this client.
   * </pre>
   *
   * <code>repeated string scope = 5;</code>
   * @return The count of scope.
   */
  public int getScopeCount() {
    return scope_.size();
  }
  /**
   * <pre>
   * The OAuth 2.0 scopes that are permitted by this client.
   * </pre>
   *
   * <code>repeated string scope = 5;</code>
   * @param index The index of the element to return.
   * @return The scope at the given index.
   */
  public java.lang.String getScope(int index) {
    return scope_.get(index);
  }
  /**
   * <pre>
   * The OAuth 2.0 scopes that are permitted by this client.
   * </pre>
   *
   * <code>repeated string scope = 5;</code>
   * @param index The index of the value to return.
   * @return The bytes of the scope at the given index.
   */
  public com.google.protobuf.ByteString
      getScopeBytes(int index) {
    return scope_.getByteString(index);
  }

  public static final int REDIRECT_URI_FIELD_NUMBER = 6;
  private volatile java.lang.Object redirectUri_;
  /**
   * <pre>
   * Redirect uri for authorization endpoint
   * </pre>
   *
   * <code>string redirect_uri = 6;</code>
   * @return The redirectUri.
   */
  @java.lang.Override
  public java.lang.String getRedirectUri() {
    java.lang.Object ref = redirectUri_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      redirectUri_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Redirect uri for authorization endpoint
   * </pre>
   *
   * <code>string redirect_uri = 6;</code>
   * @return The bytes for redirectUri.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getRedirectUriBytes() {
    java.lang.Object ref = redirectUri_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      redirectUri_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getClientIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, clientId_);
    }
    if (!getSecretBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, secret_);
    }
    for (int i = 0; i < grantTypes_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, grantTypes_.getRaw(i));
    }
    if (isScoped_ != false) {
      output.writeBool(4, isScoped_);
    }
    for (int i = 0; i < scope_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, scope_.getRaw(i));
    }
    if (!getRedirectUriBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, redirectUri_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getClientIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, clientId_);
    }
    if (!getSecretBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, secret_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < grantTypes_.size(); i++) {
        dataSize += computeStringSizeNoTag(grantTypes_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getGrantTypesList().size();
    }
    if (isScoped_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(4, isScoped_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < scope_.size(); i++) {
        dataSize += computeStringSizeNoTag(scope_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getScopeList().size();
    }
    if (!getRedirectUriBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, redirectUri_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.google.googleidentity.oauth2.client.ClientDetails)) {
      return super.equals(obj);
    }
    com.google.googleidentity.oauth2.client.ClientDetails other = (com.google.googleidentity.oauth2.client.ClientDetails) obj;

    if (!getClientId()
        .equals(other.getClientId())) return false;
    if (!getSecret()
        .equals(other.getSecret())) return false;
    if (!getGrantTypesList()
        .equals(other.getGrantTypesList())) return false;
    if (getIsScoped()
        != other.getIsScoped()) return false;
    if (!getScopeList()
        .equals(other.getScopeList())) return false;
    if (!getRedirectUri()
        .equals(other.getRedirectUri())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + CLIENT_ID_FIELD_NUMBER;
    hash = (53 * hash) + getClientId().hashCode();
    hash = (37 * hash) + SECRET_FIELD_NUMBER;
    hash = (53 * hash) + getSecret().hashCode();
    if (getGrantTypesCount() > 0) {
      hash = (37 * hash) + GRANT_TYPES_FIELD_NUMBER;
      hash = (53 * hash) + getGrantTypesList().hashCode();
    }
    hash = (37 * hash) + IS_SCOPED_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getIsScoped());
    if (getScopeCount() > 0) {
      hash = (37 * hash) + SCOPE_FIELD_NUMBER;
      hash = (53 * hash) + getScopeList().hashCode();
    }
    hash = (37 * hash) + REDIRECT_URI_FIELD_NUMBER;
    hash = (53 * hash) + getRedirectUri().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.google.googleidentity.oauth2.client.ClientDetails parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.googleidentity.oauth2.client.ClientDetails parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.googleidentity.oauth2.client.ClientDetails parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.googleidentity.oauth2.client.ClientDetails parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.googleidentity.oauth2.client.ClientDetails parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.googleidentity.oauth2.client.ClientDetails parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.googleidentity.oauth2.client.ClientDetails parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.google.googleidentity.oauth2.client.ClientDetails parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.google.googleidentity.oauth2.client.ClientDetails parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.google.googleidentity.oauth2.client.ClientDetails parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.google.googleidentity.oauth2.client.ClientDetails parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.google.googleidentity.oauth2.client.ClientDetails parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.google.googleidentity.oauth2.client.ClientDetails prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Metadata about an OAuth client registered with this server.
   * </pre>
   *
   * Protobuf type {@code googleidentity.oauth2.client.ClientDetails}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:googleidentity.oauth2.client.ClientDetails)
      com.google.googleidentity.oauth2.client.ClientDetailsOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.google.googleidentity.oauth2.client.ClientDetailsOuterClass.internal_static_googleidentity_oauth2_client_ClientDetails_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.google.googleidentity.oauth2.client.ClientDetailsOuterClass.internal_static_googleidentity_oauth2_client_ClientDetails_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.google.googleidentity.oauth2.client.ClientDetails.class, com.google.googleidentity.oauth2.client.ClientDetails.Builder.class);
    }

    // Construct using com.google.googleidentity.oauth2.client.ClientDetails.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      clientId_ = "";

      secret_ = "";

      grantTypes_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      isScoped_ = false;

      scope_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000002);
      redirectUri_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.google.googleidentity.oauth2.client.ClientDetailsOuterClass.internal_static_googleidentity_oauth2_client_ClientDetails_descriptor;
    }

    @java.lang.Override
    public com.google.googleidentity.oauth2.client.ClientDetails getDefaultInstanceForType() {
      return com.google.googleidentity.oauth2.client.ClientDetails.getDefaultInstance();
    }

    @java.lang.Override
    public com.google.googleidentity.oauth2.client.ClientDetails build() {
      com.google.googleidentity.oauth2.client.ClientDetails result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.google.googleidentity.oauth2.client.ClientDetails buildPartial() {
      com.google.googleidentity.oauth2.client.ClientDetails result = new com.google.googleidentity.oauth2.client.ClientDetails(this);
      int from_bitField0_ = bitField0_;
      result.clientId_ = clientId_;
      result.secret_ = secret_;
      if (((bitField0_ & 0x00000001) != 0)) {
        grantTypes_ = grantTypes_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000001);
      }
      result.grantTypes_ = grantTypes_;
      result.isScoped_ = isScoped_;
      if (((bitField0_ & 0x00000002) != 0)) {
        scope_ = scope_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000002);
      }
      result.scope_ = scope_;
      result.redirectUri_ = redirectUri_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.google.googleidentity.oauth2.client.ClientDetails) {
        return mergeFrom((com.google.googleidentity.oauth2.client.ClientDetails)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.google.googleidentity.oauth2.client.ClientDetails other) {
      if (other == com.google.googleidentity.oauth2.client.ClientDetails.getDefaultInstance()) return this;
      if (!other.getClientId().isEmpty()) {
        clientId_ = other.clientId_;
        onChanged();
      }
      if (!other.getSecret().isEmpty()) {
        secret_ = other.secret_;
        onChanged();
      }
      if (!other.grantTypes_.isEmpty()) {
        if (grantTypes_.isEmpty()) {
          grantTypes_ = other.grantTypes_;
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          ensureGrantTypesIsMutable();
          grantTypes_.addAll(other.grantTypes_);
        }
        onChanged();
      }
      if (other.getIsScoped() != false) {
        setIsScoped(other.getIsScoped());
      }
      if (!other.scope_.isEmpty()) {
        if (scope_.isEmpty()) {
          scope_ = other.scope_;
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          ensureScopeIsMutable();
          scope_.addAll(other.scope_);
        }
        onChanged();
      }
      if (!other.getRedirectUri().isEmpty()) {
        redirectUri_ = other.redirectUri_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.google.googleidentity.oauth2.client.ClientDetails parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.google.googleidentity.oauth2.client.ClientDetails) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object clientId_ = "";
    /**
     * <code>string client_id = 1;</code>
     * @return The clientId.
     */
    public java.lang.String getClientId() {
      java.lang.Object ref = clientId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        clientId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string client_id = 1;</code>
     * @return The bytes for clientId.
     */
    public com.google.protobuf.ByteString
        getClientIdBytes() {
      java.lang.Object ref = clientId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        clientId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string client_id = 1;</code>
     * @param value The clientId to set.
     * @return This builder for chaining.
     */
    public Builder setClientId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      clientId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string client_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearClientId() {
      
      clientId_ = getDefaultInstance().getClientId();
      onChanged();
      return this;
    }
    /**
     * <code>string client_id = 1;</code>
     * @param value The bytes for clientId to set.
     * @return This builder for chaining.
     */
    public Builder setClientIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      clientId_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object secret_ = "";
    /**
     * <code>string secret = 2;</code>
     * @return The secret.
     */
    public java.lang.String getSecret() {
      java.lang.Object ref = secret_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        secret_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string secret = 2;</code>
     * @return The bytes for secret.
     */
    public com.google.protobuf.ByteString
        getSecretBytes() {
      java.lang.Object ref = secret_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        secret_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string secret = 2;</code>
     * @param value The secret to set.
     * @return This builder for chaining.
     */
    public Builder setSecret(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      secret_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string secret = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearSecret() {
      
      secret_ = getDefaultInstance().getSecret();
      onChanged();
      return this;
    }
    /**
     * <code>string secret = 2;</code>
     * @param value The bytes for secret to set.
     * @return This builder for chaining.
     */
    public Builder setSecretBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      secret_ = value;
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringList grantTypes_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureGrantTypesIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        grantTypes_ = new com.google.protobuf.LazyStringArrayList(grantTypes_);
        bitField0_ |= 0x00000001;
       }
    }
    /**
     * <pre>
     * The OAuth 2.0 grant types that are permitted by this client.
     * </pre>
     *
     * <code>repeated string grant_types = 3;</code>
     * @return A list containing the grantTypes.
     */
    public com.google.protobuf.ProtocolStringList
        getGrantTypesList() {
      return grantTypes_.getUnmodifiableView();
    }
    /**
     * <pre>
     * The OAuth 2.0 grant types that are permitted by this client.
     * </pre>
     *
     * <code>repeated string grant_types = 3;</code>
     * @return The count of grantTypes.
     */
    public int getGrantTypesCount() {
      return grantTypes_.size();
    }
    /**
     * <pre>
     * The OAuth 2.0 grant types that are permitted by this client.
     * </pre>
     *
     * <code>repeated string grant_types = 3;</code>
     * @param index The index of the element to return.
     * @return The grantTypes at the given index.
     */
    public java.lang.String getGrantTypes(int index) {
      return grantTypes_.get(index);
    }
    /**
     * <pre>
     * The OAuth 2.0 grant types that are permitted by this client.
     * </pre>
     *
     * <code>repeated string grant_types = 3;</code>
     * @param index The index of the value to return.
     * @return The bytes of the grantTypes at the given index.
     */
    public com.google.protobuf.ByteString
        getGrantTypesBytes(int index) {
      return grantTypes_.getByteString(index);
    }
    /**
     * <pre>
     * The OAuth 2.0 grant types that are permitted by this client.
     * </pre>
     *
     * <code>repeated string grant_types = 3;</code>
     * @param index The index to set the value at.
     * @param value The grantTypes to set.
     * @return This builder for chaining.
     */
    public Builder setGrantTypes(
        int index, java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureGrantTypesIsMutable();
      grantTypes_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The OAuth 2.0 grant types that are permitted by this client.
     * </pre>
     *
     * <code>repeated string grant_types = 3;</code>
     * @param value The grantTypes to add.
     * @return This builder for chaining.
     */
    public Builder addGrantTypes(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureGrantTypesIsMutable();
      grantTypes_.add(value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The OAuth 2.0 grant types that are permitted by this client.
     * </pre>
     *
     * <code>repeated string grant_types = 3;</code>
     * @param values The grantTypes to add.
     * @return This builder for chaining.
     */
    public Builder addAllGrantTypes(
        java.lang.Iterable<java.lang.String> values) {
      ensureGrantTypesIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, grantTypes_);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The OAuth 2.0 grant types that are permitted by this client.
     * </pre>
     *
     * <code>repeated string grant_types = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearGrantTypes() {
      grantTypes_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The OAuth 2.0 grant types that are permitted by this client.
     * </pre>
     *
     * <code>repeated string grant_types = 3;</code>
     * @param value The bytes of the grantTypes to add.
     * @return This builder for chaining.
     */
    public Builder addGrantTypesBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      ensureGrantTypesIsMutable();
      grantTypes_.add(value);
      onChanged();
      return this;
    }

    private boolean isScoped_ ;
    /**
     * <pre>
     * Whether scopes for this client is limited
     * </pre>
     *
     * <code>bool is_scoped = 4;</code>
     * @return The isScoped.
     */
    @java.lang.Override
    public boolean getIsScoped() {
      return isScoped_;
    }
    /**
     * <pre>
     * Whether scopes for this client is limited
     * </pre>
     *
     * <code>bool is_scoped = 4;</code>
     * @param value The isScoped to set.
     * @return This builder for chaining.
     */
    public Builder setIsScoped(boolean value) {
      
      isScoped_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Whether scopes for this client is limited
     * </pre>
     *
     * <code>bool is_scoped = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearIsScoped() {
      
      isScoped_ = false;
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringList scope_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureScopeIsMutable() {
      if (!((bitField0_ & 0x00000002) != 0)) {
        scope_ = new com.google.protobuf.LazyStringArrayList(scope_);
        bitField0_ |= 0x00000002;
       }
    }
    /**
     * <pre>
     * The OAuth 2.0 scopes that are permitted by this client.
     * </pre>
     *
     * <code>repeated string scope = 5;</code>
     * @return A list containing the scope.
     */
    public com.google.protobuf.ProtocolStringList
        getScopeList() {
      return scope_.getUnmodifiableView();
    }
    /**
     * <pre>
     * The OAuth 2.0 scopes that are permitted by this client.
     * </pre>
     *
     * <code>repeated string scope = 5;</code>
     * @return The count of scope.
     */
    public int getScopeCount() {
      return scope_.size();
    }
    /**
     * <pre>
     * The OAuth 2.0 scopes that are permitted by this client.
     * </pre>
     *
     * <code>repeated string scope = 5;</code>
     * @param index The index of the element to return.
     * @return The scope at the given index.
     */
    public java.lang.String getScope(int index) {
      return scope_.get(index);
    }
    /**
     * <pre>
     * The OAuth 2.0 scopes that are permitted by this client.
     * </pre>
     *
     * <code>repeated string scope = 5;</code>
     * @param index The index of the value to return.
     * @return The bytes of the scope at the given index.
     */
    public com.google.protobuf.ByteString
        getScopeBytes(int index) {
      return scope_.getByteString(index);
    }
    /**
     * <pre>
     * The OAuth 2.0 scopes that are permitted by this client.
     * </pre>
     *
     * <code>repeated string scope = 5;</code>
     * @param index The index to set the value at.
     * @param value The scope to set.
     * @return This builder for chaining.
     */
    public Builder setScope(
        int index, java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureScopeIsMutable();
      scope_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The OAuth 2.0 scopes that are permitted by this client.
     * </pre>
     *
     * <code>repeated string scope = 5;</code>
     * @param value The scope to add.
     * @return This builder for chaining.
     */
    public Builder addScope(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureScopeIsMutable();
      scope_.add(value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The OAuth 2.0 scopes that are permitted by this client.
     * </pre>
     *
     * <code>repeated string scope = 5;</code>
     * @param values The scope to add.
     * @return This builder for chaining.
     */
    public Builder addAllScope(
        java.lang.Iterable<java.lang.String> values) {
      ensureScopeIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, scope_);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The OAuth 2.0 scopes that are permitted by this client.
     * </pre>
     *
     * <code>repeated string scope = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearScope() {
      scope_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The OAuth 2.0 scopes that are permitted by this client.
     * </pre>
     *
     * <code>repeated string scope = 5;</code>
     * @param value The bytes of the scope to add.
     * @return This builder for chaining.
     */
    public Builder addScopeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      ensureScopeIsMutable();
      scope_.add(value);
      onChanged();
      return this;
    }

    private java.lang.Object redirectUri_ = "";
    /**
     * <pre>
     * Redirect uri for authorization endpoint
     * </pre>
     *
     * <code>string redirect_uri = 6;</code>
     * @return The redirectUri.
     */
    public java.lang.String getRedirectUri() {
      java.lang.Object ref = redirectUri_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        redirectUri_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Redirect uri for authorization endpoint
     * </pre>
     *
     * <code>string redirect_uri = 6;</code>
     * @return The bytes for redirectUri.
     */
    public com.google.protobuf.ByteString
        getRedirectUriBytes() {
      java.lang.Object ref = redirectUri_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        redirectUri_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Redirect uri for authorization endpoint
     * </pre>
     *
     * <code>string redirect_uri = 6;</code>
     * @param value The redirectUri to set.
     * @return This builder for chaining.
     */
    public Builder setRedirectUri(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      redirectUri_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Redirect uri for authorization endpoint
     * </pre>
     *
     * <code>string redirect_uri = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearRedirectUri() {
      
      redirectUri_ = getDefaultInstance().getRedirectUri();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Redirect uri for authorization endpoint
     * </pre>
     *
     * <code>string redirect_uri = 6;</code>
     * @param value The bytes for redirectUri to set.
     * @return This builder for chaining.
     */
    public Builder setRedirectUriBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      redirectUri_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:googleidentity.oauth2.client.ClientDetails)
  }

  // @@protoc_insertion_point(class_scope:googleidentity.oauth2.client.ClientDetails)
  private static final com.google.googleidentity.oauth2.client.ClientDetails DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.google.googleidentity.oauth2.client.ClientDetails();
  }

  public static com.google.googleidentity.oauth2.client.ClientDetails getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ClientDetails>
      PARSER = new com.google.protobuf.AbstractParser<ClientDetails>() {
    @java.lang.Override
    public ClientDetails parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ClientDetails(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ClientDetails> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ClientDetails> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.googleidentity.oauth2.client.ClientDetails getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

