// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ClientDetails.proto

package com.google.googleidentity.oauth2.client;

public interface ClientDetailsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:googleidentity.oauth2.client.ClientDetails)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string client_id = 1;</code>
   * @return The clientId.
   */
  java.lang.String getClientId();
  /**
   * <code>string client_id = 1;</code>
   * @return The bytes for clientId.
   */
  com.google.protobuf.ByteString
      getClientIdBytes();

  /**
   * <code>string secret = 2;</code>
   * @return The secret.
   */
  java.lang.String getSecret();
  /**
   * <code>string secret = 2;</code>
   * @return The bytes for secret.
   */
  com.google.protobuf.ByteString
      getSecretBytes();

  /**
   * <pre>
   * The OAuth 2.0 grant types that are permitted by this client.
   * </pre>
   *
   * <code>repeated string grant_types = 3;</code>
   * @return A list containing the grantTypes.
   */
  java.util.List<java.lang.String>
      getGrantTypesList();
  /**
   * <pre>
   * The OAuth 2.0 grant types that are permitted by this client.
   * </pre>
   *
   * <code>repeated string grant_types = 3;</code>
   * @return The count of grantTypes.
   */
  int getGrantTypesCount();
  /**
   * <pre>
   * The OAuth 2.0 grant types that are permitted by this client.
   * </pre>
   *
   * <code>repeated string grant_types = 3;</code>
   * @param index The index of the element to return.
   * @return The grantTypes at the given index.
   */
  java.lang.String getGrantTypes(int index);
  /**
   * <pre>
   * The OAuth 2.0 grant types that are permitted by this client.
   * </pre>
   *
   * <code>repeated string grant_types = 3;</code>
   * @param index The index of the value to return.
   * @return The bytes of the grantTypes at the given index.
   */
  com.google.protobuf.ByteString
      getGrantTypesBytes(int index);

  /**
   * <pre>
   * Whether scopes for this client is limited
   * </pre>
   *
   * <code>bool is_scoped = 4;</code>
   * @return The isScoped.
   */
  boolean getIsScoped();

  /**
   * <pre>
   * The OAuth 2.0 scopes that are permitted by this client.
   * </pre>
   *
   * <code>repeated string scope = 5;</code>
   * @return A list containing the scope.
   */
  java.util.List<java.lang.String>
      getScopeList();
  /**
   * <pre>
   * The OAuth 2.0 scopes that are permitted by this client.
   * </pre>
   *
   * <code>repeated string scope = 5;</code>
   * @return The count of scope.
   */
  int getScopeCount();
  /**
   * <pre>
   * The OAuth 2.0 scopes that are permitted by this client.
   * </pre>
   *
   * <code>repeated string scope = 5;</code>
   * @param index The index of the element to return.
   * @return The scope at the given index.
   */
  java.lang.String getScope(int index);
  /**
   * <pre>
   * The OAuth 2.0 scopes that are permitted by this client.
   * </pre>
   *
   * <code>repeated string scope = 5;</code>
   * @param index The index of the value to return.
   * @return The bytes of the scope at the given index.
   */
  com.google.protobuf.ByteString
      getScopeBytes(int index);

  /**
   * <pre>
   * Redirect uri for authorization endpoint
   * </pre>
   *
   * <code>string redirect_uri = 6;</code>
   * @return The redirectUri.
   */
  java.lang.String getRedirectUri();
  /**
   * <pre>
   * Redirect uri for authorization endpoint
   * </pre>
   *
   * <code>string redirect_uri = 6;</code>
   * @return The bytes for redirectUri.
   */
  com.google.protobuf.ByteString
      getRedirectUriBytes();
}
